name: Website Checks

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - main
      - staging

jobs:
  lint:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Yarn
        run: npm install yarn --global
      - name: Install dependencies
        run: yarn install
      - name: Check formatting with Prettier
        run: yarn lint:prettier
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install Yarn
        run: npm install yarn --global
      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: yarn build

